--CREATE TRIGGER KITAPDURUM
--ON TBLHAREKET
--AFTER INSERT
--AS
--DECLARE @KITAP INT
--SELECT @KITAP=KÝTAP FROM inserted
--UPDATE TBLKÝTAP SET DURUM = 0 WHERE ID=@KITAP


CREATE TRIGGER KITAPDURUM2
ON TBLHAREKET
AFTER UPDATE
AS
DECLARE @KÝTAP INT
SELECT @KÝTAP=KÝTAP FROM inserted
update TBLKÝTAP SET DURUM=1 WHERE ID=@KÝTAP